name: Deploy static site to Azure Web App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3D4458AE5E3347348E0B80C46BDEDFEC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_04AA3CA735384059BACA1B43FC9B635E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DB38B586CC84419A81E385352DC9F2B5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: manju-portfolio
          package: .
